version: '3.9'

services:
  hunyuan3d:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ./output:/app/output
      - ./models:/app/models
      - ./assets:/app/assets
    environment:
      - PYTHONUNBUFFERED=1
